# Generated by Django 4.2.4 on 2023-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(blank=True, choices=[(0, '아니오'), (1, '예')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급')], default='beginner', max_length=20),
        ),
    ]
