# Generated by Django 4.2.4 on 2023-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralsummary',
            name='D',
            field=models.PositiveIntegerField(default=0, verbose_name='D'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='D_score',
            field=models.IntegerField(default=0, verbose_name='D'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Dd',
            field=models.PositiveIntegerField(default=0, verbose_name='Dd'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='EA',
            field=models.FloatField(default=0, verbose_name='EA'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='EBper',
            field=models.FloatField(default=0, verbose_name='EBper'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='ErleBnistypus',
            field=models.CharField(default='', max_length=20, verbose_name='Erlebnistypus'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='L',
            field=models.FloatField(default=0, verbose_name='lambda'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='S',
            field=models.PositiveIntegerField(default=0, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='W',
            field=models.PositiveIntegerField(default=0, verbose_name='W'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Zd',
            field=models.FloatField(default=0.0, verbose_name='Zd'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Zest',
            field=models.FloatField(default=0.0, verbose_name='Zest'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Zf',
            field=models.PositiveIntegerField(default=0, verbose_name='Zf'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Zsum',
            field=models.PositiveIntegerField(default=0, verbose_name='Zsum'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='adj_D',
            field=models.IntegerField(default=0, verbose_name='D'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='adj_es',
            field=models.FloatField(default=0, verbose_name='es'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_I',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_II',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_III',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_IV',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_IX',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_V',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_VI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_VII',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_VIII',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='app_X',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='dev_o',
            field=models.PositiveIntegerField(default=0, verbose_name='dev_o'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='dev_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='dev_+'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='dev_v',
            field=models.PositiveIntegerField(default=0, verbose_name='dev_v'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='dev_vplus',
            field=models.PositiveIntegerField(default=0, verbose_name='dev_v/+'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='eb',
            field=models.CharField(default='', max_length=20, verbose_name='eb'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='es',
            field=models.FloatField(default=0, verbose_name='es'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fqx_minus',
            field=models.PositiveIntegerField(default=0, verbose_name='fqx_minus'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fqx_none',
            field=models.PositiveIntegerField(default=0, verbose_name='fqx_none'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fqx_o',
            field=models.PositiveIntegerField(default=0, verbose_name='fqx_o'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fqx_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='fqx_+'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fqx_u',
            field=models.PositiveIntegerField(default=0, verbose_name='fqx_u'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='mq_minus',
            field=models.PositiveIntegerField(default=0, verbose_name='mq_minus'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='mq_none',
            field=models.PositiveIntegerField(default=0, verbose_name='mq_none'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='mq_o',
            field=models.PositiveIntegerField(default=0, verbose_name='mq_o'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='mq_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='mq_+'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='mq_u',
            field=models.PositiveIntegerField(default=0, verbose_name='mq_u'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_ab',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_AB'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_ag',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_AG'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_alog',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_ALOG'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_con',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_CON'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_cop',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_COP'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_cp',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_CP'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_dr',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_DR'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_dr2',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_DR2'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_dv',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_DV'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_dv2',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_DV2'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_fab',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_FAB'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_fab2',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_FAB2'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_ghr',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_GHR'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_inc',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_INC'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_inc2',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_INC2'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_mor',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_MOR'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_per',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_PER'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_phr',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_PHR'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sp_psv',
            field=models.PositiveIntegerField(default=0, verbose_name='sp_PSV'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sum6',
            field=models.PositiveIntegerField(default=0, verbose_name='raw_sum6'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wd_minus',
            field=models.PositiveIntegerField(default=0, verbose_name='wd_minus'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wd_none',
            field=models.PositiveIntegerField(default=0, verbose_name='wd_none'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wd_o',
            field=models.PositiveIntegerField(default=0, verbose_name='wd_o'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wd_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='wd_+'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wd_u',
            field=models.PositiveIntegerField(default=0, verbose_name='wd_u'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wsum6',
            field=models.PositiveIntegerField(default=0, verbose_name='wgtd_sum6'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='pair',
            field=models.CharField(max_length=20, verbose_name='쌍반응'),
        ),
        migrations.AlterField(
            model_name='structuralsummary',
            name='R',
            field=models.IntegerField(verbose_name='반응수'),
        ),
    ]
