# Generated by Django 4.2.4 on 2023-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_structuralsummary_d_structuralsummary_d_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecode',
            name='loc_num',
            field=models.IntegerField(null=True, verbose_name='영역번호'),
        ),
    ]
