# Generated by Django 4.2.4 on 2023-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_remove_structuralsummary_left_eb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralsummary',
            name='Isol',
            field=models.FloatField(default=0.0, verbose_name='Isol Index'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Lvl_2',
            field=models.PositiveIntegerField(default=0, verbose_name='lvl-2'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='Ma_Mp',
            field=models.CharField(default='', max_length=20, verbose_name='Ma:Mp'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='PTI',
            field=models.CharField(default='xxxxx', max_length=15, verbose_name='PTI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='W_D_dd',
            field=models.CharField(default='', max_length=15, verbose_name='W:D:Dd'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='W_M',
            field=models.CharField(default='', max_length=15, verbose_name='W:M'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='an_xy',
            field=models.PositiveIntegerField(default=0, verbose_name='An+Xy'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='ego',
            field=models.FloatField(default=0.0, verbose_name='egocentric'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fdn',
            field=models.PositiveIntegerField(default=0, verbose_name='selfperception_FD'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='fr_rf',
            field=models.PositiveIntegerField(default=0, verbose_name='Fr+rF'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='h_prop',
            field=models.CharField(default='', max_length=15, verbose_name='H:(H)+Hd+(Hd)'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='human_cont',
            field=models.PositiveIntegerField(default=0, verbose_name='human_content'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='intel',
            field=models.FloatField(default=0.0, verbose_name='intellecutalization index'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='popular',
            field=models.PositiveIntegerField(default=0, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='s_minus',
            field=models.PositiveIntegerField(default=0, verbose_name='S-%'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='wda_per',
            field=models.FloatField(default=0.0, verbose_name='WDA%'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='x_minus_per',
            field=models.FloatField(default=0.0, verbose_name='X-%'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='x_plus_per',
            field=models.FloatField(default=0.0, verbose_name='X+%'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='xa_per',
            field=models.FloatField(default=0.0, verbose_name='XA%'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='xu_per',
            field=models.FloatField(default=0.0, verbose_name='Xu%'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(help_text='YYYY-DD-MM 형식으로 입력(예: 2000-08-01)', verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='client',
            name='testDate',
            field=models.DateField(help_text='YYYY-DD-MM 형식으로 입력(예: 2023-05-01)', verbose_name='검사일'),
        ),
    ]
