# Generated by Django 4.2.4 on 2023-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_structuralsummary_isol_structuralsummary_lvl_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='검사 당시 나이'),
        ),
    ]
