# Generated by Django 4.2.4 on 2023-11-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_client_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralsummary',
            name='CDI',
            field=models.CharField(default='xxxxx', max_length=15, verbose_name='CDI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='DEPI',
            field=models.CharField(default='xxxxxxx', max_length=15, verbose_name='DEPI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='HVI',
            field=models.CharField(default='xxxxxxx', max_length=15, verbose_name='HVI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='HVI_except',
            field=models.CharField(default='', max_length=15, verbose_name='HVI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='HVI_premise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='OBS',
            field=models.CharField(default='xxxxxxxxx', max_length=15, verbose_name='HVI'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='OBS_posi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='SCON',
            field=models.CharField(default='xxxxxxxxxx', max_length=15, verbose_name='S-CON'),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sumCDI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sumDEPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sumHVI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sumPTI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralsummary',
            name='sumSCON',
            field=models.IntegerField(default=0),
        ),
    ]
