# Generated by Django 4.2.4 on 2023-11-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_structuralsummary_cdi_structuralsummary_depi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralsummary',
            old_name='W_D_dd',
            new_name='W_D_Dd',
        ),
    ]
