# Generated by Django 4.2.4 on 2023-11-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_rename_w_d_dd_structuralsummary_w_d_dd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecode',
            name='response_num',
            field=models.IntegerField(null=True, verbose_name='반응번호'),
        ),
    ]
