# Generated by Django 4.2.4 on 2023-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_alter_responsecode_z_alter_responsecode_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecode',
            name='Z',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='조직화 점수'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='card',
            field=models.CharField(max_length=5, null=True, verbose_name='카드번호'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='코멘트'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='content',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='내용인'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='determinants',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='결정인'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='dev_qual',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='발달질'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='form_qual',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='형태질'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='inquiry',
            field=models.TextField(blank=True, null=True, verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='location',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='반응영역'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='pair',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='쌍반응'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='popular',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='평범반응'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='반응내용'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='rotation',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='카드방향'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='special',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='특수점수'),
        ),
        migrations.AlterField(
            model_name='responsecode',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='반응시간'),
        ),
    ]
