# Generated by Django 4.2.4 on 2023-11-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_alter_responsecode_z_alter_responsecode_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecode',
            name='temp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='임시저장여부'),
        ),
    ]
