# Generated by Django 4.2.4 on 2024-02-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_responsecode_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecode',
            name='temp',
        ),
    ]
