# Generated by Django 4.2.10 on 2024-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_remove_responsecode_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
