# Generated by Django 4.2.10 on 2025-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_alter_responsecode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_psych_dx',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='현재 치료 관련 진단명'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_psych_treatment',
            field=models.CharField(choices=[('none', '없음'), ('treat', '치료중')], default='none', max_length=10, verbose_name='현재 정신과 치료 유무'),
        ),
        migrations.AddField(
            model_name='client',
            name='evaluation_purpose',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='평가 목적'),
        ),
        migrations.AddField(
            model_name='client',
            name='examiner_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='검사자 이름(실명)'),
        ),
        migrations.AddField(
            model_name='client',
            name='past_psych_dx',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='과거 치료 관련 진단명'),
        ),
        migrations.AddField(
            model_name='client',
            name='past_psych_treatment',
            field=models.CharField(choices=[('none', '없음'), ('yes', '치료받은 적 있음')], default='none', max_length=10, verbose_name='과거 정신과 치료 유무'),
        ),
        migrations.AddField(
            model_name='client',
            name='rorschach_history',
            field=models.CharField(choices=[('0', '0회'), ('1', '1회'), ('2', '2회'), ('3+', '3회 이상')], default='0', max_length=3, verbose_name='로르샤흐 검사 수검 이력'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(help_text='YYYY-MM-DD 형식으로 입력(예: 2000-08-01)', verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='client',
            name='testDate',
            field=models.DateField(help_text='YYYY-MM-DD 형식으로 입력(예: 2023-05-01)', verbose_name='검사일'),
        ),
    ]
